/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "helper-parent"
include(":helper")
include(":helper-lilypad")
include(":helper-sql")
include(":helper-redis")
include(":helper-mongo")
include(":helper-profiles")
include(":helper-js")
